import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Script  src="https://cdn.jsdelivr.net/npm/js-confetti@latest/dist/js-confetti.browser.js"></Script>
      </body>
    </html>
  );
}
